# -*- coding: utf-8 -*-
"""pybasic_Astha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvBBX4OLsTylNiBX1CGrsWZO1dV_ufbh

# Expressions, Operators, Control statements
"""





"""# Operators
- Arithmetic (+, -, *, /, //, %)
- Relational (<, >, <=, >=, !=, ==)
- Shift (>>, <<)
- Assignment (=)
- Logical (and, or, not)
- Bitwise (&, |, !)
- 'in' and 'not in' operator

# << and >>

if n=8 (1000 in binary), n>>1 will give 100 after shifting bits by 1 place to right. 
                         n<<1 will give 10000 after shifting bits by 1 place to left.
"""

n=10
print(n,'binary',format(n,'b'))
print(n,'* 2=',n<<1, format(n<<1,'b'))
print(n,'/ 2=',n>>1,format(n>>1,'b'))

# logical
x = True
y = False
print('x and y is',x and y) # Output: x and y is False
print('x or y is',x or y) # Output: x or y is True
print('not x is',not x) # Output: not x is False

# bitwise
x=10 
y=4
print(x & y) 
print(x | y)
print(x ^ y)

# in and not in

x = 'Hello world'
print('j' in x)    # Output: True
print('h' not in x)   # Output: True

# perform operations on cs

import cmath
a=complex(20+7j)
b=complex(5+3j)
print('a+b',a+b)
print('a-b',a-b)
print('a*b',a*b)
print('a/b',a/b)



"""### Task1 Write a program in python to calculate area of triangle when all three sides are given.
- s=(a+b+c)/2
- area =  √(s(s-a)(s-b)(s-c) )
"""



a = float(input('Enter first side: '))
b = float(input('Enter second side: '))
c = float(input('Enter third side: '))
s = (a + b + c) / 2
area = (s*(s-a)*(s-b)*(s-c))*0.5
print('The area of the triangle is %0.2f' %area)

"""# Control Statements

### Decisions (if-else)

# simple if-else
if(cond):
    stmt
else:
    stmt

# if-else-if
if(cond):
    stmt
elif(cond):
    stmt
    .
    .
    .
else: 
    stmt

# nested if-else
                            if(cond):
                                stmt
                                if(cond):
                                    stmt1
                            else:
                                if(cond):
                                    stmt3
                                else:
                                    stmt4

### Task2: Write a proram that accept a lowercase/uppercase character from the user and check whether the character is a vowel or consonant.
"""

ch = input("Enter a character: ")

if(ch=='A' or ch=='a' or ch=='E' or ch =='e' or ch=='I'
 or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'):
    print(ch, "is a Vowel")
else:
    print(ch, "is a Consonant")

# write your code after this line
str=input('Enter a letter: ').lower()
if(str == 'a' or str == 'e' or str == 'i' or str == 'o' or str == 'u'):
  print(str,'is vowel')
else:
  print(str,'is consonant')

"""### Task3: Write a program to check whether given character is a digit or a character in lowercase or uppercase alphabet. Hint: ASCII value of digit is between 48 to 58 and Lowercase characters in the range of 97 to122, uppercase is between 65 and 90)."""



# write your code after this line
str = input("Enter a digit(ACSII) or character: ")
str=ord(str)
if str>=97 and str<=122:
  print("lower case letter")
if str>=48 and str<=58:
  print("is a digit")
if str>=65 and str<=90:
  print("upper case letter")

"""### Repetition or loop
- while loop
- for loop

#### While loop

initialization of loop variable
while( condition ):
    stmt 1
    stmt 2
    ...
    update loop variable

##### Task 4: Write a program in Python to print table of any number 'n' provided by user using while loop.
"""

num = int(input("Enter the number: "))

print("Multiplication Table of", num)
for i in range(1, 11):
   print(num,"X",i,"=",num * i)

# write your code after this line
num=int(input("enter a number"))
i=1
while i <= 10:
  product = num*i
  print(num, " * ", i, " = ", product, "\n")
  i = i + 1



"""##### Task 5: Write a program in Python to evaluate the following series using while loop:
    
    1! + 2! + 3! + 4! ...+ n!
hint: use math.factorial(n) function to calculate factorial of number n.
"""

import math
num=int(input("enter any number"))
sum=0
while(num):
  sum+=math.factorial(num)
  num-=1
print("the sum is",sum)

"""##### Task 6: Write a program in Python to enter the numbers till the user wants and at the end it should display the maximum number entered using while loop."""

str='Y'
i=[]
n=0
i[n]=int(input("Enter a number"))
str=input("Do you want to enter more numbers??(Y/N):- ")
n=n+1
 while(str=='Y'):
print(max(i))

str='Y'
i=[]
n=0
i[n]=int(input("Enter a number"))
str=input("Do you want to enter more numbers??(Y/N):- ")
n=n+1
while(str=='Y'):
  print(max(i))



"""### for loop

for iterable_var_name in range(terminating_value):
    stmt 1
    stmt 2
    ...
    
 for iterable_var_name in range(initial_value,terminating_value):
    stmt 1
    stmt 2
    ...
    
 for iterable_var_name in range(initial_value,terminating_value,updation):
    stmt 1
    stmt 2
    ...
"""

# factorial
n=int(input('Enter a number '))
fact=1
for i in range(n,1,-1):
    fact=fact*i
print(n,'! =',fact)

"""##### Task 7:Write a program in Python to print all numbers from 0 to 9 except 3 and 6 using a for loop."""

for i in range(10):
  if(i==3 or i==6):
    continue;
  else:
    print("number :",i)

"""#### 2 Write a program in Python to get 10 numbers from user using a for loop. The program should print the count of positive numbers, negative numbers and zeroes entered by the user."""

count1=0
count2=0
count3=0
for i in range (10):
  y=int(input("enter the number"))
  if(y>0):
    count1+=1
  elif(y<0):
    count2+=1
  else:
    count3+=1
print("positive :{}".format(count1))
print("negative :{}".format(count2))
print("zero :{}".format(count3))